source-file ~/.config/tmux/tmux.reset.conf

# --- Terminal ---
set -g default-terminal "tmux-256color"
set -as terminal-features ",tmux-256color:RGB"
set -g default-terminal "${TERM}"

# --- General ---
set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position bottom       # macOS / darwin style
setw -g mode-keys vi

# --- Borders ---
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'omerxx/tmux-floax'

# --- Floax ---
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-bind 'f'
set -g @floax-change-path 'true'

# --- Session X ---
set -g @sessionx-bind-zo-new-window 'ctrl-y'
set -g @sessionx-auto-accept 'off'
set -g @sessionx-bind 'o'
set -g @sessionx-x-path '~/repos/dotfiles'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-custom-paths-subdirectories 'false'
set -g @sessionx-filter-current 'false'

# --- Fzf URL ---
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

# --- Resurrect / Continuum ---
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

# --- Rose Pine Theme ---
set -g @rose_pine_variant 'main'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'
set -g @rose_pine_directory 'on'
set -g @rose_pine_date_time '%H:%M'
set -g @rose_pine_show_pane_directory 'on'
set -g @rose_pine_left_separator ' > '
set -g @rose_pine_right_separator ' < '
set -g @rose_pine_window_status_separator '  '

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'
run '~/.config/tmux/plugins/tpm/tpm'
