# First remove *all* keybindings
# unbind-key -a
# Now reinsert all the regular tmux keys

# --- Session ---
bind ^D detach
bind S choose-session
bind * list-clients

# --- Windows ---
bind ^C new-window -c "$HOME"
bind W new-window
bind H previous-window
bind L next-window
bind ^A last-window
bind ^W list-windows
bind w list-windows
bind '"' choose-window
bind r command-prompt "rename-window %%"

# --- Panes ---
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind | split-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind z resize-pane -Z
bind c kill-pane
bind x swap-pane -D
bind P set pane-border-status
bind * setw synchronize-panes

# --- Pane Resizing ---
bind -r -T prefix , resize-pane -L 20
bind -r -T prefix . resize-pane -R 20
bind -r -T prefix - resize-pane -D 7
bind -r -T prefix = resize-pane -U 7

# --- Copy Mode (vi) ---
bind-key -T copy-mode-vi v send-keys -X begin-selection

# --- Utility ---
bind ^X lock-server
bind ^L refresh-client
bind : command-prompt
bind R source-file ~/.config/tmux/tmux.conf
bind K send-keys "clear"\; send-keys "Enter"
